version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    volumes:
      - ./app:/app               # Enables live-reloading for backend changes
      - /app/__pycache__          # Optional: Exclude cache files
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"               # Expose React development server
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for some Docker setups to watch files
    volumes:
      - ./frontend/graphdb:/frontend # Enables live-reloading for frontend changes
